import { StyleSheet, Dimensions } from 'react-native';
const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: { flex: 1, paddingHorizontal: 20, paddingTop: 60, alignItems: 'center' },
  modeSelector: { flexDirection: 'row', gap: 8, marginBottom: 40, position: 'relative' },
  modeIndicator: { position: 'absolute', top: 0, bottom: 0, borderRadius: 20, borderWidth: 1.5 },
  modeButton: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 14, paddingVertical: 10, borderRadius: 20, gap: 6 },
  modeEmoji: { fontSize: 16 },
  modeLabel: { fontSize: 13, fontWeight: '600' },
  timerContainer: { width: 260, height: 260, justifyContent: 'center', alignItems: 'center', marginBottom: 32 },
  glowCircle: { position: 'absolute' },
  timerTextContainer: { position: 'absolute', alignItems: 'center' },
  timerText: { fontSize: 56, fontWeight: '200', fontVariant: ['tabular-nums'], letterSpacing: 2 },
  timerSubtext: { fontSize: 13, marginTop: 4, fontWeight: '600', letterSpacing: 1.5, textTransform: 'uppercase' },
  sessionDots: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 32 },
  sessionDot: { width: 12, height: 12, borderRadius: 6, borderWidth: 2 },
  sessionCountText: { fontSize: 12, marginLeft: 8, fontWeight: '500' },
  addSessionButton: { width: 22, height: 22, borderRadius: 11, borderWidth: 1.5, justifyContent: 'center', alignItems: 'center', marginLeft: 6 },
  addSessionText: { fontSize: 14, fontWeight: '700', lineHeight: 16 },
  successBanner: { paddingVertical: 6, paddingHorizontal: 16, backgroundColor: '#0a3622', borderRadius: 20, marginBottom: 24, borderWidth: 1, borderColor: '#198754' },
  successBannerText: { color: '#d1e7dd', fontSize: 13, fontWeight: '600' },
  controls: { flexDirection: 'row', alignItems: 'center', gap: 28, marginBottom: 36 },
  controlButton: { width: 50, height: 50, borderRadius: 25, borderWidth: 1.5, justifyContent: 'center', alignItems: 'center' },
  playButton: { width: 76, height: 76, borderRadius: 38, justifyContent: 'center', alignItems: 'center', shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.3, shadowRadius: 8, elevation: 6 },
  tipCard: { paddingHorizontal: 20, paddingVertical: 12, borderRadius: 16, borderWidth: 1 },
  tipText: { fontSize: 13, textAlign: 'center' },
  taskChip: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 10, borderRadius: 20, borderWidth: 1.5, marginBottom: 20, minWidth: 160, justifyContent: 'center' },
  taskChipText: { fontSize: 14, fontWeight: '600', marginRight: 4 },
  taskChipClear: { padding: 2, marginLeft: 6 },
  topRightControls: { position: 'absolute', top: 20, right: 20, zIndex: 10, flexDirection: 'row', gap: 16 },
  headerButton: { padding: 5 },
  statsCard: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-around', paddingVertical: 16, borderRadius: 16, borderWidth: 1, marginTop: 16, width: '100%' },
  statsItem: { alignItems: 'center', flex: 1 },
  statsDivider: { width: 1, height: 30, backgroundColor: 'rgba(150,150,150,0.3)' },
  statsValue: { fontSize: 18, fontWeight: '700', marginBottom: 4 },
  statsLabel: { fontSize: 12, textTransform: 'uppercase', letterSpacing: 0.5 },
});
